### ISSUE TITLE
Combat looters don't read loot 

### ISSUE THREAD

**Issue by CatsUnicorns** [matheussampaio/ao-loot-logger#12]
since the last update the combat does not read anything, it does not read anything, and I get an error folder.

**Comment by matheussampaio** [comment]
Have you tried the version v4?

https://github.com/matheussampaio/ao-loot-logger/releases

**Comment by matheussampaio** [comment]
It worked?

**Comment by CatsUnicorns** [comment]
Yes

Obtener Outlook para Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by CatsUnicorns** [comment]
Hi bro, I need help whit loot loggerr viewer
