### ISSUE TITLE
VirusTotal

### ISSUE THREAD

**Issue by BElluu** [matheussampaio/ao-loot-logger#24]
https://www.virustotal.com/gui/file/7491c9e5941a7aaec135fc8468143237062e0f7d4afcc676ea17572ff8a2eb23

Someone can check that?

**Comment by matheussampaio** [comment]
The code is open and compiled here in github. I'm not sure why this tool flags as a trojan (probability because it reads packets from the network?), but if you don't feel safe using programs from the internet (and you shouldn't), you can always read the code to see what it does.
