### ISSUE TITLE
Error when i run the ao looter

### ISSUE THREAD

**Issue by rageking23** [matheussampaio/ao-loot-logger#37]
![image](https://github.com/matheussampaio/ao-loot-logger/assets/166640745/66cc6202-8da0-477c-b363-1b83007461c3)

I dont understand why

**Comment by madvac** [comment]
try going into C:/Users/{username}/AppData/Local/Temp and delete the caxa folder.

**Comment by rageking23** [comment]
Thank you!! I think it is working nowwww!!!!

**Comment by rageking23** [comment]
Thank you for the fix !!!!!
