### ISSUE TITLE
ev IDs

### ISSUE THREAD

**Issue by madvac** [matheussampaio/ao-loot-logger#42]
Hello,

i cant post links in discord.
i found this at ao data client

https://github.com/ao-data/albiondata-client/blob/master/client/eventtype_string.go

but i think it is not what u want.

**Comment by matheussampaio** [comment]
Do you know how they generate that file? If we could figure that out, the process to update the loot logger after every patch could be reduced drastically (maybe even automated).


https://github.com/ao-data/albiondata-client/blob/master/client/eventtype_string.go#L1
```
// Code generated by "stringer -type=EventType"; DO NOT EDIT.
```

The first line suggest the file is generated with a script, but I couldn't find it.

**Comment by madvac** [comment]
i was looking for it before, but i cant find it.

**Comment by madvac** [comment]
hello,
it looks they change IDs again. :-(
