### ISSUE TITLE
libpcap old version

### ISSUE THREAD

**Issue by IlabSentuser** [matheussampaio/ao-loot-logger#5]
Hello,
when trying to run the binary for linux you run into the problem showed below:

`Error: libpcap.so.0.8: cannot open shared object file: No such file or directory
    at process.dlopen (pkg/prelude/bootstrap.js:2114:28)
    at Object.Module._extensions..node (node:internal/modules/cjs/loader:1183:18)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
    at Module.require (pkg/prelude/bootstrap.js:1719:31)
    at require (node:internal/modules/cjs/helpers:102:18)
    at Object.<anonymous> (/snapshot/ao-loot-logger/node_modules/cap/lib/Cap.js:3:13)
    at Module._compile (pkg/prelude/bootstrap.js:1794:22)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1153:10) {
  code: 'ERR_DLOPEN_FAILED'
}`

In several linux systems that version is already unavailable and in others it is but for some other reason you cant upgrade it. Is any way that the current version can be used? Or a posible workaround?

**Comment by enyonyelison** [comment]
I'm also having the same error @matheussampaio 
![image](https://user-images.githubusercontent.com/13843354/156897327-10a974c4-902c-4687-8bde-1aa79931b951.png)

**Comment by matheussampaio** [comment]
> In several linux systems that version is already unavailable and in others it is but for some other reason you cant upgrade it. Is any way that the current version can be used? Or a posible workaround?

Maybe we could update the build scripts to install from source or something more recent. Unfortunately, I don't have a linux machine to test it out.

You can find the steps to build for linux [here](https://github.com/matheussampaio/ao-loot-logger/blob/main/.github/workflows/build.yml#L40).

**Comment by IlabSentuser** [comment]
Hello, I think I was not clear enough, it is not that the library itself does not exist. libcap is installed in my system, it is just that the version is not the one required for ao-loot-logger to run, the binding is against libcap.so.0.8 which in my system does not exist, or rather it does but with the name libcap.so; i tried, among other things, to symlink the standard libcap to the required one but it did not work for reasons unknown to me.
In my distribution is not really possible to downgrade libcap, and even if i did, i would still hit the same problem, as libcap.so.0.8 is expected, that is the case for some other distributions as well. I did try to play around with the code to build the binary, but the error keeps occurring. I don't really know how to develop in NodeJS so maybe what I did is of no use.
Also, now that I explored the code a little I think that is not your responsibility as i think you just use the module called cap, which should be the one responsible for fixing this I suppose. Can you confirm me this?
I do have linux as my OS and the willingness to help with this completely, so if someone (maintainer or someone else) knows how to change the version that the software requires of libcap i can test it.

**Comment by matheussampaio** [comment]
You are correct, `cap` is the one using this old dependency. I can't do much there.
